language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - sys-img-x86-android-26

before_install:
  - chmod +x gradlew
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # include tools for avdmanager
  - sdkmanager tools
  # Install system image.
  - sdkmanager "system-images;android-26;default;x86"

#Set up emulator
before_script:
  - echo no | avdmanager create avd -n test -k "system-images;android-26;default;x86"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &